[package]
name = "ocr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
screenshots = "0.8.5"
core-graphics = "0.23.1"
cocoa = "0.25.0"
objc = "0.2.7"
anyhow = "1.0.75"
